In [1]:
import pandas as pd
import numpy as np
import numpy as np
import matplotlib.pyplot as plt

In [2]:
paper13 = pd.read_csv('/home/shared/splus_gaia/data/h-alpha-selection-marina/MC/Be_stars/Iqbal&Keller_2013.csv')

In [5]:
paper13

,system,cluster,log_age_Myr,radius_arcmin,radius_glatt_arcmin,MSTO_Vmag,cluster_NBe_NB,cluster_NBe_frac,field_NBe_NB,field_NBe_frac,N_field_cont
0,LMC,NGC2004,7.2,1.85,1.45,14.6,19 (22)/207,0.084,42 (43)/827,0.048,4.64
1,LMC,NGC1805,7.6,0.99,0.85,16.0,4/46,0.080,16/463,0.033,0.47
2,LMC,ESO86SC2,7.5,1.18,1.10,15.7,3/35,0.079,12/217,0.052,0.51
3,LMC,NGC2025,8.0,0.95,0.95,17.2,1/18,0.053,21/344,0.058,0.57
4,LMC,LMC0461,8.1,0.76,0.80,17.5,0/10,0.000,10/113,0.081,0.17
5,LMC,NGC1755,7.4,1.17,1.02,15.3,4/81,0.047,17/771,0.022,0.70
6,LMC,NGC1774,7.7,0.76,0.80,16.3,6/45,0.118,10 (11)/447,0.022,0.17
7,LMC,NGC1951,7.7,1.25,0.80,16.3,1/32,0.030,25/378,0.062,0.19
8,LMC,LMC0899,8.1,1.62,0.85,17.5,0/14,0.000,2/89,0.022,0.17
9,LMC,NGC1902,8.0,1.00,0.85,17.2,2/10,0.167,6/181,0.032,0.18
10,LMC,NGC1839,7.9,0.78,0.80,16.9,0/38,0.000,39/1220,0.031,0.70
11,SMC,NGC330,7.4,1.18,1.33,15.9,27 (28)/136,0.166,80 (81)/976,0.076,3.59
12,SMC,NGC231,7.9,0.63,0.90,17.4,6/14,0.300,47/392,0.107,0.56
13,SMC,NGC220,8.0,1.34,0.60,17.7,5/11,0.313,21/179,0.105,1.14
14,SMC,SMC0707,7.4,0.55,0.42,15.8,2/16,0.111,146 (148)/1922,0.071,1.32
15,SMC,SMC0483,7.9,1.11,0.60,17.4,0/33,0.000,37 (41)/497,0.069,1.35
16,SMC,SMC0028,8.0,1.61,0.85,17.7,0/11,0.000,4/78,0.049,0.31
17,SMC,NGC306,7.4,0.45,0.55,15.8,1/14,0.067,74/958,0.072,0.44
18,SMC,NGC376,7.5,0.69,0.90,16.1,3/16,0.158,67 (70)/793,0.078,0.97
19,SMC,SMC0720,7.6,0.61,0.42,16.5,1/9,0.100,42 (43)/737,0.054,0.49
20,SMC,SMC0213,7.6,0.63,0.60,16.5,1/17,0.056,60 (61)/1119,0.051,0.71
21,SMC,SMC0302,7.6,0.97,0.43,17.1,1/26,0.037,38/511,0.069,1.06
22,SMC,NGC299,7.4,0.61,0.45,15.8,1/9,0.100,55 (57)/757,0.068,0.59
23,SMC,SMC0263,7.8,0.79,0.48,17.1,1/13,0.071,39/654,0.056,0.71
24,SMC,SMC0314,7.4,0.59,0.55,15.8,0/24,0.000,52/795,0.061,0.55

In [4]:
paper13["cluster"] = (
    paper13["cluster"]
    .str.split(",").str[0]      # pega antes da vírgula
    .str.replace("-", "", regex=False)
    .str.replace(" ", "", regex=False)
)

In [6]:
my_frac = pd.read_csv('/home/shared/splus_gaia/data/h-alpha-selection-marina/MC/Be_stars/stellar_clusters_age/be_stars_fraction_per_cluster.csv')

In [10]:
my_frac

,cluster_Names,counts_be_stars,counts_all_stars,fraction_be_stars,[M/H],amaj,Cross-ID,Vmag,e_Vmag,LogAge_total,ra_deg,dec_deg
0,BOB1,3.0,360,0.008333,,3.70,NaN,NaN,NaN,8.20,11.391667,-73.257222
1,BOB11,1.0,376,0.002660,,3.00,NaN,NaN,NaN,,13.537500,-72.710833
2,BOB12,15.0,3543,0.004234,,4.50,NaN,NaN,NaN,7.60,13.841667,-72.782500
3,BOB13,54.0,7138,0.007565,,9.00,NaN,NaN,NaN,6.80,14.491667,-72.548333
4,BOB14,33.0,9597,0.003439,,7.00,NaN,NaN,NaN,6.90,14.908333,-72.747222
...,...,...,...,...,...,...,...,...,...,...,...,...
5563,ZHTSP2,0.0,114,0.000000,NaN,0.95,NaN,NaN,NaN,NaN,75.833330,-66.981110
5564,ZHT12,0.0,60,0.000000,NaN,0.65,NaN,NaN,NaN,NaN,79.175000,-67.803060
5565,ZHT2,0.0,112,0.000000,NaN,0.60,NaN,NaN,NaN,NaN,75.620830,-66.610830
5566,ZHT3,0.0,135,0.000000,NaN,1.50,NaN,NaN,NaN,NaN,76.475000,-66.733330
5567,ZHT7,0.0,385,0.000000,NaN,0.35,NaN,NaN,NaN,NaN,75.612500,-67.801390

In [9]:
my_frac["cluster_Names"] = (
    my_frac["cluster_Names"]
    .str.split(",").str[0]      # pega antes da vírgula
    .str.replace("-", "", regex=False)
    .str.replace(" ", "", regex=False)
)

In [12]:
comp = pd.merge(paper13, my_frac, left_on='cluster', right_on='cluster_Names', how='inner')
# comp.plot.scatter(x='fraction_Be_stars', y='Be_star_fraction_pp2013')
# plt.xlabel('My Be star fraction')
# plt.ylabel('Paper Iqbal & Keller 2013 Be star fraction')
# plt.title('Comparison of Be star fractions per cluster')
# plt.grid()
# plt.show()

In [13]:
comp

,system,cluster,log_age_Myr,radius_arcmin,radius_glatt_arcmin,MSTO_Vmag,cluster_NBe_NB,cluster_NBe_frac,field_NBe_NB,field_NBe_frac,...,counts_all_stars,fraction_be_stars,[M/H],amaj,Cross-ID,Vmag,e_Vmag,LogAge_total,ra_deg,dec_deg
0,LMC,NGC2004,7.2,1.85,1.45,14.6,19 (22)/207,0.084,42 (43)/827,0.048,...,1305,0.019923,NaN,3.0,NaN,NaN,NaN,NaN,82.666670,-67.286940
1,LMC,NGC1805,7.6,0.99,0.85,16.0,4/46,0.080,16/463,0.033,...,552,0.014493,NaN,1.8,NaN,NaN,NaN,NaN,75.587500,-66.111670
2,LMC,NGC2025,8.0,0.95,0.95,17.2,1/18,0.053,21/344,0.058,...,424,0.004717,NaN,1.9,NaN,NaN,NaN,NaN,83.137500,-71.716940
3,LMC,NGC1755,7.4,1.17,1.02,15.3,4/81,0.047,17/771,0.022,...,419,0.021480,NaN,2.2,"NGC1755,SL99,ESO56SC28,KMHK272",9.385,0.1,7.400000095367432,73.808330,-68.204720
4,LMC,NGC1774,7.7,0.76,0.80,16.3,6/45,0.118,10 (11)/447,0.022,...,370,0.008108,NaN,1.7,NaN,NaN,NaN,NaN,74.525000,-67.242220
5,LMC,NGC1951,7.7,1.25,0.80,16.3,1/32,0.030,25/378,0.062,...,323,0.015480,NaN,1.7,NaN,NaN,NaN,NaN,81.520830,-66.597220
6,LMC,NGC1902,8.0,1.00,0.85,17.2,2/10,0.167,6/181,0.032,...,268,0.000000,NaN,1.7,NaN,NaN,NaN,NaN,79.575000,-66.627220
7,SMC,NGC330,7.4,1.18,1.33,15.9,27 (28)/136,0.166,80 (81)/976,0.076,...,152,0.026316,-0.82,2.8,NaN,NaN,NaN,7.63,14.077917,-72.463333
8,SMC,NGC231,7.9,0.63,0.90,17.4,6/14,0.300,47/392,0.107,...,142,0.007042,,1.8,NaN,NaN,NaN,7.87,10.278333,-73.351111
9,SMC,NGC220,8.0,1.34,0.60,17.7,5/11,0.313,21/179,0.105,...,13,0.000000,,1.2,NaN,NaN,NaN,8.03,10.127083,-73.401944
10,SMC,NGC306,7.4,0.45,0.55,15.8,1/14,0.067,74/958,0.072,...,70,0.071429,-0.01,1.1,NaN,NaN,NaN,7.70,13.562500,-72.241389
11,SMC,NGC376,7.5,0.69,0.90,16.1,3/16,0.158,67 (70)/793,0.078,...,1105,0.010860,-0.40,1.8,NaN,NaN,NaN,7.40,15.973750,-72.825556
12,SMC,NGC299,7.4,0.61,0.45,15.8,1/9,0.100,55 (57)/757,0.068,...,42,0.000000,-0.01,0.9,NaN,NaN,NaN,7.40,13.354167,-72.196389